const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const {acquire, launchBrowser} = require('../replay.cjs');
const baseUrl = process.env.BASE_URL || 'http://127.0.0.1:4173';
const outputDir = process.env.OUTPUT_DIR || 'artifacts/browser-tests';
(async () => {
  const browser = await launchBrowser();
  const errors = [];
  const results = [];
  const page = await browser.newPage({acceptDownloads: true, viewport: {width: 1440, height: 1000}});
  page.on('pageerror', error => errors.push(error.message));
  try {
    await fs.mkdir(outputDir, {recursive: true});
    await page.goto(baseUrl);
    assert.match(await page.title(), /Hackathon replica/);
    await page.screenshot({path: path.join(outputDir, 'portal-chooser.png'), fullPage: true});
    const a = await acquire(page, {baseUrl, source: 'upright', outputDir});
    assert.equal(a.manifest.row_count, 128);
    assert.equal(a.manifest.order_count, 128);
    results.push('PASS Upright actual CSV download, row dates, SHA-256 and manifest');
    await page.getByRole('button', {name: 'Preview', exact: true}).first().click();
    await page.locator('#report-preview').waitFor({state: 'visible'});
    assert.equal(await page.locator('#preview-table tbody tr').count(), 20);
    await page.screenshot({path: path.join(outputDir, 'upright-report.png'), fullPage: true});
    const same = await acquire(page, {baseUrl, source: 'upright', outputDir});
    assert.deepEqual(a.bytes, same.bytes);
    results.push('PASS Same request produces byte-identical CSV');
    const b = await acquire(page, {baseUrl, source: 'upright', startDate: '2026-10-01', endDate: '2026-10-02', outputDir});
    assert.equal(b.manifest.row_count, 256);
    assert.notEqual(a.manifest.file_checksum, b.manifest.file_checksum);
    results.push('PASS Alternate dates produce different file and correct inclusive coverage');
    const cash = await acquire(page, {baseUrl, source: 'cash_monkey', outputDir});
    assert.equal(cash.manifest.row_count, 32);
    assert.equal(cash.manifest.order_count, 30);
    await page.getByRole('button', {name: 'Preview report', exact: true}).click();
    await page.locator('#report-preview').waitFor({state: 'visible'});
    await page.screenshot({path: path.join(outputDir, 'cash-monkey-report.png'), fullPage: true});
    results.push('PASS Cash Monkey report download and separate unit/order counts');
    await page.goto(`${baseUrl}/upright/reports/paid-orders`);
    await page.getByRole('button', {name: 'Test controls', exact: true}).click();
    await page.getByLabel('Scenario', {exact: true}).selectOption('delayed');
    const delayed = await acquire(page, {baseUrl, source: 'upright', outputDir});
    assert.equal(delayed.manifest.row_count, 128);
    results.push('PASS Delayed generation waits for a real download');
    await page.getByRole('button', {name: 'Test controls', exact: true}).click();
    await page.getByLabel('Scenario', {exact: true}).selectOption('session-expired');
    await page.getByRole('button', {name: 'Generate report', exact: true}).click();
    await page.locator('#messages.error').waitFor();
    assert.match(await page.locator('#messages').innerText(), /session expired/i);
    assert.equal(await page.locator('#generate-report').isEnabled(), true);
    results.push('PASS Expired session fails visibly');
    await page.getByLabel('Scenario', {exact: true}).selectOption('missing-report');
    await page.getByRole('button', {name: 'Generate report', exact: true}).click();
    await page.locator('#messages.error').waitFor();
    assert.match(await page.locator('#messages').innerText(), /unavailable/i);
    results.push('PASS Missing report has no successful download');
    await page.getByLabel('Scenario', {exact: true}).selectOption('changed-label');
    assert.equal(await page.getByRole('button', {name: 'Generate report', exact: true}).count(), 0);
    assert.equal(await page.getByRole('button', {name: 'Build export', exact: true}).count(), 1);
    await assert.rejects(acquire(page, {baseUrl, source: 'upright', outputDir, timeout: 1200}), /Timeout/);
    results.push('PASS DOM drift stops baseline replay instead of guessing');
    await page.goto(`${baseUrl}/upright/reports/paid-orders`);
    await page.getByRole('button', {name: 'Test controls', exact: true}).click();
    await page.getByLabel('Scenario', {exact: true}).selectOption('normal');
    await page.getByLabel('Start date', {exact: true}).fill('2026-10-02');
    await page.getByLabel('End date', {exact: true}).fill('2026-10-01');
    await page.getByRole('button', {name: 'Generate report', exact: true}).click();
    assert.match(await page.locator('#messages').innerText(), /start date.*before/i);
    results.push('PASS Reversed dates fail without generating a report');
    await page.goto(`${baseUrl}/upright`);
    await page.screenshot({path: path.join(outputDir, 'upright-home.png'), fullPage: true});
    await page.goto(`${baseUrl}/cash-monkey/reports`);
    await page.screenshot({path: path.join(outputDir, 'cash-monkey-reports.png'), fullPage: true});
    await page.setViewportSize({width: 390, height: 844});
    for (const route of ['/', '/upright', '/upright/reports/paid-orders', '/cash-monkey/reports/orders']) {
      await page.goto(baseUrl + route);
      const width = await page.evaluate(() => ({page: document.documentElement.scrollWidth, viewport: innerWidth}));
      assert(width.page <= width.viewport, `Horizontal page overflow on ${route}: ${JSON.stringify(width)}`);
    }
    await page.screenshot({path: path.join(outputDir, 'mobile-report.png'), fullPage: true});
    assert.deepEqual(errors, [], 'Browser JavaScript errors');
    results.push('PASS Mobile layouts and no browser JavaScript errors');
    await fs.writeFile(path.join(outputDir, 'results.txt'), results.join('\n') + '\n');
    console.log(results.join('\n'));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
